language: node_js

node_js:
  - "8"

services:
  - docker

cache: yarn

git:
  submodules: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - git submodule update --init
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sed -i.bak 's/package.json/package.json yarn.lock/' .docker/vue-storefront/docker/vue-storefront/Dockerfile

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.test.yml build

script:
  - yarn bundle
  - make build
  - yarn cypress
