language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

services:
  - elasticsearch
  - redis

cache:
  yarn: true
  directories:
    - ~/.cache

git:
  submodules: false

before_install:
  - git submodule update --init

before_script:
  - make bundle
  - make start

script:
  - yarn e2e
