language: node_js

node_js:
  - 10

services:
  - docker
  - elasticsearch
  - redis

cache:
  yarn: true
  directories:
    - ~/.cache

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sed -i.bak 's/package.json/package.json yarn.lock/' .docker/vue-storefront/docker/vue-storefront/Dockerfile

install: yarn
script:
  - yarn lint
  - make bundle
  - make ci
