language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

services:
  - docker
  - elasticsearch
  - redis

cache:
  yarn: true
  directories:
    - ~/.cache

git:
  submodules: false

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - git submodule update --init

before_script:
  - yarn bundle
  - make build

script:
  - yarn cypress
