language: node_js
node_js:
  - 10

git:
  submodules: false

services:
  - docker
  - elasticsearch
  - redis

cache:
  yarn: true
  directories:
    - ~/.cache

addons:
  apt:
    packages:
      - libgconf-2-4

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0

before_install:
  - git submodule update --init

install: yarn
script:
  - yarn lint
  - make bundle
  - make ci-start
  - yarn test:ci
