version: '2.4'

services: 
  storefront-api:
    depends_on: 
      - elasticsearch
      - redis
    labels:
      bundle: "vue-storefront-api"
  storefront-ui:
    labels:
      bundle: "vue-storefront"

volumes:
  esdat1: null
